### ISSUE TITLE
Initial commit to enable pull requests

### ISSUE THREAD

**Issue by Tomarchelone** [RustAudio/mp3#3]
I wrote some code we could start with which is based on this previous attempt: https://github.com/Aceeri/mptree. But it seems like it is impossible to create a pull request to an empty repository. Maybe make an initial commit?

**Comment by est31** [comment]
Thanks for showing interest in working on MP3!

I'm not sure yet whether we can use mptree as a basis. It depends on licensing mostly :). I'm in contact with the author right now.

**Comment by est31** [comment]
This is fixed now, and PR was filed as #4 .
